# Optional: override secret sources.
# By default, docker-compose.yml expects secrets files at ./secrets/*

secrets:
  discord_bot_token:
    file: ./secrets/discord_bot_token
  matrix_homeserver:
    file: ./secrets/matrix_homeserver
  matrix_user_id:
    file: ./secrets/matrix_user_id
  matrix_password:
    file: ./secrets/matrix_password
